service: subscription-service

package:
  individually: true
  

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    dockerImage: python:3.9-slim-buster
    layer: true
    

functions:
  app:
    package:
      patterns:
        - "src/**"
        - "!requirements.txt"
        - "!.vscode/**"
        - '!.pylint'
        - "!package.json"
        - "!package-lock.json"
        - "!.serverless/**"
        - "!.virtualenv/**"
        - "!node_modules/**"
        - "!venv_wsl/**"

    handler: src/main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - Ref: PythonRequirementsLambdaLayer

    events:
      - http:
          method: any
          path: /{proxy+}